### ISSUE TITLE
不知道能不能加上地图样式选项

### ISSUE THREAD

**Issue by imcake** [Icemap/go-map-downloader#1]
不知道能不能加上地图样式选项
比如Google 卫星的可以把道路POI之类的都不显示，只显示卫星地图

**Comment by Icemap** [comment]
It can not remove the road, but I can offer an option to hide the label for you.
BTW, we can use English (or Both English and Chinese) to make the communication here. It can let more people know what are we talking about.

**Comment by Icemap** [comment]
Added Support. PTAL @imcake

**Comment by Icemap** [comment]
If there has any question. Please fell free to open it again.
