### ISSUE TITLE
加了 -google-label=false 之后，名称确实隐藏了但是虚影街道没有隐藏。

### ISSUE THREAD

**Issue by PredawnRaziel** [Icemap/go-map-downloader#4]
这是在Google地图中直接去掉标签的样子：
![image](https://github.com/user-attachments/assets/ed8b0509-2061-40b4-b98c-5ff267d81699)

这是加了 -google-label=false 之后生成图的样子：
![image](https://github.com/user-attachments/assets/36bda605-a5a4-456d-9759-d42e79ce9f5a)

请问我还需要加什么参数来调整吗？

**Comment by PredawnRaziel** [comment]
哦哦，这个参数前面加了 lite 参数就解决了。不好意思。

**Comment by Icemap** [comment]
没关系哈，有啥问题提 issue 就好。我先关闭了，有什么问题你可以 reopen 它。
